[package]
name = "bimef"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
tpe = "0.2"

[dev-dependencies]
anyhow = "1"
png = "0.17"
structopt = "0.3"
